AWS_ACCESS_KEY: "AKIAYBMJOMYMDJCGNUPW"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "artelostudio2"
# AWS_REGION: "ca-central-1"
AWS_REGION:     "us-east-1"
SECRET_KEY: 'sk_test_IR46rHkriyqVh5f41e3mS4fv00If8awAiC'
PUBLISHABLE_KEY: 'pk_test_TjIRwKTjn83JTtcC9w1W1OZu008uTn499b'